USE 2010s_Retrosheet;

DROP TABLE IF EXISTS ProductiveOutData;
CREATE TABLE ProductiveOutData AS
SELECT BAT_ID, START_BASES_CD, END_BASES_CD, RBI_CT FROM events 
WHERE START_BASES_CD != 0 AND START_BASES_CD != 1 AND START_BASES_CD
AND OUTS_CT < 2
AND (EVENT_CD = 2 OR EVENT_CD = 3 OR EVENT_CD = 19);

SELECT r.LAST_NAME_TX, r.FIRST_NAME_TX, COUNT(p.START_BASES_CD) AS PrOO,
SUM(CASE p.START_BASES_CD < p.END_BASES_CD WHEN TRUE THEN 1 ELSE 0 END) AS PrO FROM ProductiveOutData p
LEFT JOIN rosters r ON p.BAT_ID = r.PLAYER_ID 
GROUP BY r.LAST_NAME_TX, r.FIRST_NAME_TX
ORDER BY PrOO DESC;